version: '3.6'

services:

  # mcafee ==================================================
  chatdev:
    image: chatdev.dev
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    environment:      
      LOG_LEVEL: DEBUG
    volumes:
      - ./:/app
    networks:
      - kafka_net
    ports:
      - 8000:8000


# Networks ================================================
networks:
  kafka_net:
    name: kafka_net
